import json
import runpy
import shlex
import sys

import pytest
from typer.testing import CliRunner

from cartage.cli import app

runner = CliRunner()
FILES = {"dagster": "orchestration/dagster/materials.py", "prefect": "orchestration/prefect/materials.py"}
CLEAN_CSV = "material,industry,type,description,uom,status\n100001,M,FERT,Pump housing,EA,active\n"
# Runs the cartage under test, whatever environment the orchestrator runtime is in.
CARTAGE = shlex.join([sys.executable, "-c", "from cartage.cli import app; app()"])


def cli(project, *args):
    return runner.invoke(app, ["-C", str(project), *args])


def schedule(project, target, extra=""):
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(pipeline.read_text().replace(
        "schedule:\n", f"schedule:\n  {target}:\n    schedule: '0 3 * * *'\n{extra}", 1))


def generate(project, target):
    result = cli(project, "generate", "--target", target)
    assert result.exit_code == 0, result.output
    content = (project / FILES[target]).read_text()
    compile(content, FILES[target], "exec")
    return content


@pytest.mark.parametrize("target", ["dagster", "prefect"])
def test_generates_thin_file_calling_cartage_run(project, target):
    schedule(project, target)
    content = generate(project, target)
    assert content.startswith("# Generated by cartage")
    assert '        "run", \'pipelines/materials.yaml\',\n        "--env", env,\n    ]\n' in content
    assert "os.environ.get('CARTAGE_ENV', 'prd')" in content
    assert "os.path.dirname(__file__), '../..'" in content
    assert "'0 3 * * *'" in content
    assert generate(project, target) == content  # deterministic


def test_dagster_specifics(project):
    schedule(project, "dagster", "    tags: { team: data }\n    timezone: Europe/Brussels\n")
    content = generate(project, "dagster")
    assert "@dg.op(name='materials_cartage_run')" in content
    assert "@dg.job(name='materials', tags={'cartage': 'true', 'team': 'data'})" in content
    assert "execution_timezone='Europe/Brussels'" in content


def test_prefect_specifics_and_no_schedule(project):
    schedule(project, "prefect", "    retries: 2\n    name: nightly_materials\n")
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(pipeline.read_text().replace("    schedule: '0 3 * * *'\n    retries", "    retries", 1))
    result = cli(project, "generate", "--target", "prefect")
    assert result.exit_code == 0, result.output
    content = (project / "orchestration/prefect/nightly_materials.py").read_text()
    assert "@flow(name='nightly_materials', retries=2, log_prints=True)" in content
    assert "    cartage_run.serve(\n        name='nightly_materials',\n        tags=['cartage'],\n    )\n" in content


def test_pipelines_without_that_schedule_are_skipped(project):
    result = cli(project, "generate", "--target", "dagster")
    assert result.exit_code == 0, result.output
    assert not (project / "orchestration").exists()


@pytest.mark.parametrize("target, extra, message", [
    ("dagster", "    imgae: x\n", "Unknown Dagster setting(s): imgae"),
    ("prefect", "    name: nightly-run\n", "Invalid Prefect name 'nightly-run'"),
    ("prefect", "    tags: [2024-01-01]\n", "Prefect setting 'tags' contains a date value"),
])
def test_invalid_settings(project, target, extra, message):
    schedule(project, target, extra)
    result = cli(project, "generate", "--target", target)
    assert result.exit_code == 2
    assert message in result.output


def test_project_template_override(project):
    schedule(project, "prefect")
    (project / "templates/prefect").mkdir(parents=True)
    (project / "templates/prefect/prefect.py.j2").write_text(
        '{% extends "cartage/prefect.py.j2" %}\n{% block extra %}\n# custom footer for {{ name }}\n{% endblock %}\n')
    assert generate(project, "prefect").rstrip().endswith("# custom footer for materials")


def _run_ready(project, target, monkeypatch):
    (project / "data/sample/materials.csv").write_text(CLEAN_CSV)
    schedule(project, target, f"    env: dev\n    command: {json.dumps(CARTAGE)}\n")  # JSON string = YAML string
    generate(project, target)
    monkeypatch.delenv("CARTAGE_ENV", raising=False)
    return runpy.run_path(str(project / FILES[target]))


def test_generated_dagster_job_runs_cartage(project, monkeypatch):
    pytest.importorskip("dagster")
    module = _run_ready(project, "dagster", monkeypatch)
    assert module["job"].execute_in_process().success
    assert (project / ".cartage/state/materials/dev/state.json").is_file()


def test_generated_prefect_flow_runs_cartage(project, monkeypatch):
    pytest.importorskip("prefect")
    module = _run_ready(project, "prefect", monkeypatch)
    module["cartage_run"]()
    assert (project / ".cartage/state/materials/dev/state.json").is_file()
