import json
import os
import shlex
import subprocess
import sys

from typer.testing import CliRunner

from cartage.cli import app

runner = CliRunner()
DAG = "dags/materials_to_sap.py"


def cli(project, *args):
    return runner.invoke(app, ["-C", str(project), *args])


def generate(project):
    result = cli(project, "generate")
    assert result.exit_code == 0, result.output
    return (project / DAG).read_text()


def test_generates_valid_thin_dag(project):
    content = generate(project)
    compile(content, DAG, "exec")
    assert content.startswith(
        "# Generated by cartage 0.3.0 from pipelines/materials.yaml"
    )
    assert (
        "from airflow.providers.standard.operators.bash import BashOperator" in content
    )
    assert "dag_id='materials_to_sap'" in content
    assert "schedule='0 3 * * *'" in content
    assert "tags=['sap', 'materials']" in content
    assert "default_args = {'owner': 'data-team', 'retries': 1}" in content
    assert (
        """bash_command='cartage' + " --project-dir " + shlex.quote(PROJECT_DIR) + " run " + """
        """"pipelines/materials.yaml --env {{ var.value.get('cartage_env', 'prd') }}","""
    ) in content
    assert "os.path.dirname(__file__), '..'" in content
    assert "k8s" not in content


def test_generation_is_deterministic(project):
    assert generate(project) == generate(project)


def test_settings_merge_image_and_custom_operator(project):
    settings = project / "cartage.yaml"
    settings.write_text(
        settings.read_text().replace(
            "    dags_dir: dags\n",
            "    dags_dir: dags\n    operator: operators.datacoves:DatacovesBashOperator\n    operator_args: { retries: 2, pool: default }\n",
        )
    )
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            "    tags: [sap, materials]\n",
            "    tags: [sap, materials]\n    image: reg/cartage:1\n    operator_args: { pool: sap }\n",
        )
    )
    content = generate(project)
    compile(content, DAG, "exec")
    assert "from operators.datacoves import DatacovesBashOperator" in content
    assert "DatacovesBashOperator(" in content
    assert "pool='sap'," in content and "retries=2," in content
    assert "from kubernetes.client import models as k8s" in content
    assert "image='reg/cartage:1'" in content


def test_project_template_override_extends_blocks(project):
    (project / "templates/airflow").mkdir(parents=True)
    (project / "templates/airflow/dag.py.j2").write_text(
        '{% extends "cartage/airflow_dag.py.j2" %}\n{% block extra %}\n# custom footer for {{ dag_id }}\n{% endblock %}\n'
    )
    content = generate(project)
    compile(content, DAG, "exec")
    assert content.rstrip().endswith("# custom footer for materials_to_sap")


def test_check_detects_stale_files(project):
    generate(project)
    assert cli(project, "generate", "--check").exit_code == 0
    (project / DAG).write_text("# edited by hand\n")
    stale = cli(project, "generate", "--check")
    assert stale.exit_code == 1
    assert "materials_to_sap.py" in stale.output


def test_show_context(project):
    result = cli(project, "generate", "--show-context", "materials")
    assert result.exit_code == 0, result.output
    assert json.loads(result.output)["dag_id"] == "materials_to_sap"


def test_unknown_setting_is_rejected(project):
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            "    tags: [sap, materials]\n", "    tags: [sap, materials]\n    imgae: x\n"
        )
    )
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Unknown Airflow setting(s): imgae" in result.output


def _edit_pipeline(project, extra):
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            "    tags: [sap, materials]\n", "    tags: [sap, materials]\n" + extra
        )
    )


def test_invalid_operator_args_keys_rejected(project):
    for key in ("pool-x", "task_id"):
        _edit_pipeline(project, f"    operator_args: {{ {key}: 1 }}\n")
        result = cli(project, "generate")
        assert result.exit_code == 2
        assert "Invalid Airflow operator_args key" in result.output
        _edit_pipeline(project, "")  # no-op; file reset below
        (project / "pipelines/materials.yaml").write_text(
            (project / "pipelines/materials.yaml")
            .read_text()
            .replace(f"    operator_args: {{ {key}: 1 }}\n", "")
        )


def test_unquoted_yaml_date_rejected(project):
    _edit_pipeline(project, "    default_args: { start_date: 2024-01-01 }\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "quote it in YAML" in result.output


def test_dag_id_path_traversal_rejected(project):
    _edit_pipeline(project, "    dag_id: ../evil\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Invalid Airflow dag_id" in result.output


CLEAN_CSV = "material,industry,type,description,uom,status\n100001,M,FERT,Pump housing,EA,active\n100002,M,ROH,Steel,KG,active\n"


def test_generated_bash_command_runs(project):
    """Rebuild the DAG's bash_command as Airflow would (no Airflow needed) and run it."""
    (project / "data/materials/materials.csv").write_text(CLEAN_CSV)
    line = next(
        l
        for l in generate(project).splitlines()
        if l.strip().startswith("bash_command=")
    )
    expr = line.strip().removeprefix("bash_command=").removesuffix(",")
    command = eval(expr, {"shlex": shlex, "PROJECT_DIR": str(project)})
    command = command.replace("{{ var.value.get('cartage_env', 'prd') }}", "dev")
    env = {
        **os.environ,
        "PATH": os.path.dirname(sys.executable) + os.pathsep + os.environ["PATH"],
    }
    result = subprocess.run(
        command, shell=True, env=env, capture_output=True, text=True, timeout=300
    )
    assert result.returncode == 0, result.stdout + result.stderr
