import json
import os
import shlex
import subprocess
import sys

from typer.testing import CliRunner

from cartage.cli import app

runner = CliRunner()
DAG = "dags/materials.py"


def cli(project, *args):
    return runner.invoke(app, ["-C", str(project), *args])


def generate(project):
    result = cli(project, "generate")
    assert result.exit_code == 0, result.output
    return (project / DAG).read_text()


def test_generates_valid_thin_dag(project):
    content = generate(project)
    compile(content, DAG, "exec")
    assert content.startswith(
        "# Generated by cartage 0.8.1 from pipelines/materials.yaml"
    )
    assert "from airflow.decorators import dag, task" in content
    assert "@dag(\n" in content and "def materials():" in content
    assert content.rstrip().endswith("materials()")
    assert "    @task.bash\n    def cartage_run():" in content
    assert "dag_id='materials'" in content
    assert "schedule='0 3 * * *'" in content
    assert "tags=['cartage']" in content
    assert "default_args = {'owner': 'data-team', 'retries': 1}" in content
    assert (
        """return 'cartage' + " --project-dir " + shlex.quote(PROJECT_DIR) + " run " + """
        """"pipelines/materials.yaml --env {{ var.value.get('cartage_env', 'prd') }}"\n"""
    ) in content
    assert "os.path.dirname(__file__), '..'" in content
    assert "k8s" not in content


def test_generation_is_deterministic(project):
    assert generate(project) == generate(project)


def test_settings_merge_image_and_custom_decorator(project):
    settings = project / "cartage.yaml"
    settings.write_text(
        settings.read_text().replace(
            "    dags_dir: dags\n",
            "    dags_dir: dags\n    task_decorator: datacoves_bash\n    operator_args: { retries: 2, pool: default }\n",
        )
    )
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            '    schedule: "0 3 * * *"\n',
            '    schedule: "0 3 * * *"\n' "    image: reg/cartage:1\n    operator_args: { pool: sap }\n",
        )
    )
    content = generate(project)
    compile(content, DAG, "exec")
    assert "    @task.datacoves_bash(\n" in content
    assert "pool='sap'," in content and "retries=2," in content
    assert "from kubernetes.client import models as k8s" in content
    assert "image='reg/cartage:1'" in content


def test_project_template_override_extends_blocks(project):
    (project / "templates/airflow").mkdir(parents=True)
    (project / "templates/airflow/dag.py.j2").write_text(
        '{% extends "cartage/airflow_dag.py.j2" %}\n{% block extra %}\n# custom footer for {{ dag_id }}\n{% endblock %}\n'
    )
    content = generate(project)
    compile(content, DAG, "exec")
    assert content.rstrip().endswith("# custom footer for materials")


def test_sink_pipelines_need_remote_state_on_the_orchestrator(project):
    config = project / "cartage.yaml"
    config.write_text(config.read_text().replace("prd: {connection: landing, prefix: cartage/state/}",
                                                 "prd: {path: .cartage/state}"))
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "env 'prd' keeps that state on local disk" in result.output


def test_check_detects_stale_files(project):
    generate(project)
    assert cli(project, "generate", "--check").exit_code == 0
    (project / DAG).write_text("# edited by hand\n")
    stale = cli(project, "generate", "--check")
    assert stale.exit_code == 1
    assert "materials.py" in stale.output


def test_show_context(project):
    result = cli(project, "generate", "--show-context", "materials")
    assert result.exit_code == 0, result.output
    assert json.loads(result.output)["dag_id"] == "materials"


def test_unknown_setting_is_rejected(project):
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            '    schedule: "0 3 * * *"\n', '    schedule: "0 3 * * *"\n' "    imgae: x\n"
        )
    )
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Unknown Airflow setting(s): imgae" in result.output


def _edit_pipeline(project, extra):
    pipeline = project / "pipelines/materials.yaml"
    pipeline.write_text(
        pipeline.read_text().replace(
            '    schedule: "0 3 * * *"\n', '    schedule: "0 3 * * *"\n' + extra
        )
    )


def test_invalid_operator_args_keys_rejected(project):
    for key in ("pool-x", "task_id"):
        _edit_pipeline(project, f"    operator_args: {{ {key}: 1 }}\n")
        result = cli(project, "generate")
        assert result.exit_code == 2
        assert "Invalid Airflow operator_args key" in result.output
        _edit_pipeline(project, "")  # no-op; file reset below
        (project / "pipelines/materials.yaml").write_text(
            (project / "pipelines/materials.yaml")
            .read_text()
            .replace(f"    operator_args: {{ {key}: 1 }}\n", "")
        )


def test_unquoted_yaml_date_rejected(project):
    _edit_pipeline(project, "    default_args: { start_date: 2024-01-01 }\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "quote it in YAML" in result.output


def test_dag_id_path_traversal_rejected(project):
    _edit_pipeline(project, "    dag_id: ../evil\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Invalid Airflow dag_id" in result.output


CLEAN_CSV = "material,industry,type,description,uom,status\n100001,M,FERT,Pump housing,EA,active\n100002,M,ROH,Steel,KG,active\n"


def test_generated_bash_command_runs(project):
    """Rebuild the DAG's bash_command as Airflow would (no Airflow needed) and run it."""
    (project / "data/sample/materials.csv").write_text(CLEAN_CSV)
    line = next(
        l
        for l in generate(project).splitlines()
        if l.strip().startswith("return ")
    )
    expr = line.strip().removeprefix("return ")
    command = eval(expr, {"shlex": shlex, "PROJECT_DIR": str(project)})
    command = command.replace("{{ var.value.get('cartage_env', 'prd') }}", "dev")
    env = {
        **os.environ,
        "PATH": os.path.dirname(sys.executable) + os.pathsep + os.environ["PATH"],
    }
    result = subprocess.run(
        command, shell=True, env=env, check=False, capture_output=True, text=True, timeout=300
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_airflow_connection_references_become_task_env(project):
    connections = project / "connections.yaml"
    connections.write_text(connections.read_text().replace(
        '      dev: {transport: mock, client: "100"}\n',
        '      dev: {transport: mock, client: "${airflow:sap_conn.schema}", user: "${airflow:sap-conn.extra.user.name}"}\n'))
    connections.write_text(connections.read_text() + "\n  unused:\n    type: sap_bapi\n    envs:\n      dev: { client: \"${airflow:other.login}\" }\n")
    settings = project / "cartage.yaml"
    settings.write_text(settings.read_text().replace("    dags_dir: dags\n", "    dags_dir: dags\n    task_env: { UV_CACHE_DIR: /tmp/uv_cache }\n"))

    content = generate(project)

    compile(content, DAG, "exec")
    assert "'CARTAGE_AIRFLOW__SAP_CONN__SCHEMA': \"{{ conn.get('sap_conn').schema or '' }}\"" in content
    assert "'CARTAGE_AIRFLOW__SAP_CONN__EXTRA__USER__NAME': \"{{ conn.get('sap-conn').extra_dejson['user']['name'] or '' }}\"" in content
    assert "'UV_CACHE_DIR': '/tmp/uv_cache'" in content and "append_env=True," in content
    assert "other" not in content  # only connections this pipeline uses


def test_no_task_env_without_references(project):
    assert "env=" not in generate(project)


def test_invalid_airflow_reference_field(project):
    connections = project / "connections.yaml"
    connections.write_text(connections.read_text().replace('client: "100"}', 'client: "${airflow:sap_conn.passwd}" }', 1))
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Invalid Airflow connection reference '${airflow:sap_conn.passwd}'" in result.output


def test_run_resolves_airflow_references_from_task_env(project, monkeypatch):
    connections = project / "connections.yaml"
    connections.write_text(connections.read_text().replace('client: "100"}', 'client: "${airflow:sap_conn.schema}" }', 1))
    (project / "data/sample/materials.csv").write_text(
        "material,industry,type,description,uom,status\n100001,M,FERT,Pump housing,EA,active\n")
    missing = cli(project, "run", "materials", "--engine", "python")
    assert missing.exit_code == 2
    assert "CARTAGE_AIRFLOW__SAP_CONN__SCHEMA" in missing.output

    monkeypatch.setenv("CARTAGE_AIRFLOW__SAP_CONN__SCHEMA", "100")
    assert cli(project, "run", "materials", "--engine", "python").exit_code == 0


def test_schedule_block_can_wrap_the_schedule(project):
    (project / "templates/airflow").mkdir(parents=True)
    (project / "templates/airflow/dag.py.j2").write_text(
        '{% extends "cartage/airflow_dag.py.j2" %}\n'
        "{% block schedule %}set_schedule({{ super() }}){% endblock %}\n")
    content = generate(project)
    assert "    schedule=set_schedule('0 3 * * *'),\n" in content
    assert generate(project) == content


def test_old_operator_setting_points_to_task_decorator(project):
    _edit_pipeline(project, "    operator: a.b:C\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "operator was replaced by task_decorator" in result.output


def test_dependencies_add_up_and_become_uv_with_flags(project):
    settings = project / "cartage.yaml"
    settings.write_text(settings.read_text().replace(
        "    dags_dir: dags\n",
        '    dags_dir: dags\n    command: uvx --from "cartage>=0.7" cartage\n    dependencies: ["dlt[snowflake]", pandas]\n'))
    _edit_pipeline(project, "    dependencies: [pandas, pyarrow]\n")
    content = generate(project)
    compile(content, DAG, "exec")
    assert "return \"uvx --with 'dlt[snowflake]' --with pandas --with pyarrow --from 'cartage>=0.7' cartage\" + " in content


def test_dependencies_need_a_uv_command(project):
    _edit_pipeline(project, "    dependencies: [pandas]\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "Airflow dependencies need a uv command" in result.output


def test_default_args_and_schedule_from_functions(project):
    _edit_pipeline(project, "    default_args_from: utils.dags:set_default_args\n"
                            "    default_args: { owner: Ana, owner_email: ana@example.com }\n"
                            "    schedule_from: utils.dags:set_schedule\n")
    content = generate(project)
    compile(content, DAG, "exec")
    assert "from utils.dags import set_default_args\nfrom utils.dags import set_schedule\n" in content
    # project default_args (owner, retries) merge with the pipeline's, then become keyword arguments
    assert "default_args = set_default_args(owner='Ana', retries=1, owner_email='ana@example.com')\n" in content
    assert "    schedule=set_schedule('0 3 * * *'),\n" in content


def test_invalid_function_reference_rejected(project):
    _edit_pipeline(project, "    schedule_from: utils.set_schedule\n")
    result = cli(project, "generate")
    assert result.exit_code == 2
    assert "must be 'module.path:function'" in result.output


def test_dag_function_name_is_a_python_identifier(project):
    _edit_pipeline(project, "    dag_id: 1-materials.sap\n")
    result = cli(project, "generate")
    assert result.exit_code == 0, result.output
    content = (project / "dags/1-materials.sap.py").read_text()
    compile(content, "dag", "exec")
    assert "def _1_materials_sap():" in content and "dag_id='1-materials.sap'" in content
